config/routes.rb
Rails.application.routes.draw do
  root to: "pictures#index"
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, except: [:index]
  resources :favorites, only: [:create, :destroy, :index]
  resources :pictures do
    collection do
      post :confirm
    end
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user

  mount_uploader :image, ImageUploader

  validates :image, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pictures
  has_many :favorites, dependent: :destroy

  mount_uploader :image, ImageUploader

  has_secure_password

  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }

  before_validation { email.downcase! }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper

  before_action :login_required

  private

  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorite = Favorite.all

  end

  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_path, notice: "#{favorite.picture.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_path, notice: "#{favorite.picture.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  def index
    @pictures = Picture.all
  end

  def new
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end
  end

  def confirm
    @picture = current_user.pictures.build(picture_params)
    render :new if @picture.invalid?
  end

  def create
    @picture = current_user.pictures.build(picture_params)
    if params[:back]
      render :new
    else
      if @picture.save
        PictureMailer.post_mail(@picture).deliver
        redirect_to pictures_path, notice: "投稿を作成しました！"
      else
        render :new
      end
    end
  end

  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  def edit
  end

  def update
    if @picture.update(picture_params)
      redirect_to pictures_path, notice: "投稿を編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @picture.destroy
    redirect_to pictures_path, notice:"投稿を削除しました！"
  end

  private

  def picture_params
    params.require(:picture).permit(:image, :image_cache, :content)
  end

  def set_picture
    @picture = Picture.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id  #インスタンス化した時のid
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id), notice:"ログインしました！"
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path, notice: "プロフィールを更新しました！"
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to user_path, notice:"画像を削除しました！"
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation,
                                 :image, :image_cache)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/views/favorites/index.html.erb
<h1>お気に入り一覧</h1>
<table>
  <tr>
    <th>投稿者</th>
    <th>イメージ</th>
    <th>コメント</th>
  <tr/>
  <% @favorite.each do |favorite| %>
    <tr>
      <td><%= favorite.picture.user.name %></td>
      <td><%= image_tag(favorite.picture.image.url, size: '100x100') %></td>
      <td><%= favorite.picture.content %></td>
      <td><%= link_to '詳細を確認', picture_path(favorite.picture.id) %></td>  </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SessionLogin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="header clearfix">
      <nav>
        <ul class="top_menu clearfix">
          <% if logged_in? %>
            <li class="top_left"><i>&nbsp;Insta</i></li>
            <li class="top_left"><%= link_to "投稿一覧", pictures_path %></li>
            <li class="top_right"><%= link_to "プロフィール", user_path(current_user.id) %></li>
            <li class="top_right"><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></li>
          <% else %>
            <li><%= link_to "アカウント作成", new_user_path %></li>
            <li><%= link_to "ログイン", new_session_path %></li>
          <% end %>
        </ul>
      </nav>
    </header>
    <main>
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>
      <%= yield %>
    </main>
    <footer>
    </footer>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: @picture, local: true, url: choose_new_or_edit) do |form| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @picture.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="picture_title">
    <%= form.label :image %>
    <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>
  <div class="picture_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>
 <%= link_to "投稿一覧", pictures_path %>

app/views/pictures/confirm.html.erb
<h3>確認画面</h3>
<%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
  <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>
  <p>イメージ:<%= @picture.image %></p>
  <p>テキスト:<%= @picture.content %></p>
  <%= form.submit  "登録する" %>
<% end %>
<%= form_with(model: @picture, url: new_picture_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>
  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/pictures/edit.html.erb
<h2>投稿を編集する</h2>
  <%= render 'form' %>

app/views/pictures/index.html.erb
<h1>投稿一覧</h1>
<p><%= notice %></p>
<table>
  <tr>
    <th>投稿者</th>
    <th>イメージ</th>
    <th>コメント</th>
  <tr/>
  <% @pictures.each do |picture| %>
    <tr>
      <td><%= picture.user.name %></td>
      <td><%= image_tag picture.image.url, size: '100x100' %></td>
      <td><%= picture.content %></td>
      <td><%= link_to '詳細を確認', picture_path(picture.id) %></td>
      <% if picture.user_id == current_user.id %>
        <td><%= link_to '/ 投稿を編集', edit_picture_path(picture.id) %></td>
        <td><%= link_to '/ 投稿を削除', picture_path(picture.id),
                method: :delete,data: { confirm: '削除しますか？' } %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>
<br>
<%= link_to '新規投稿', new_picture_path %>

app/views/pictures/new.html.erb
<h2>投稿を作成する</h2>
  <%= render 'form' %>

app/views/pictures/show.html.erb
<h1>投稿詳細画面</h1>
<% unless @picture.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(picture_id: @picture.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>
<p id="notice"><%= notice %></p>
<p>
  <strong>Image:</strong>
  <%= image_tag @picture.image.url %>
</p>
<p>コメント: <%= @picture.content %></p>
<% if @picture.user_id == current_user.id %>
  <%= link_to '投稿を編集', edit_picture_path(@picture) %> |
<% end %>
<%= link_to '一覧に戻る', pictures_path %>

app/views/users/edit.html.erb
<h1>Profile edit</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :image %>
  <%= image_tag @user.image.url if @user.image && @user.image.url %>
  <%= f.file_field :image %>
  <%= f.hidden_field :image_cache %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "プロフィール編集完了" %>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<% if @user.image.url != nil %>
  <%= image_tag @user.image.url, size: '200x200' %>
<% else %>
  <%= image_tag 'no_image.png', size: '200x200' %>
<% end %>
<p><%= link_to 'プロフィール編集', edit_user_path(@user) %> |
   <%= link_to 'お気に入り一覧', favorites_path(@user) %>
</p>